import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version",
};

serve(async (req) => {
  if (req.method === "OPTIONS") return new Response("ok", { headers: corsHeaders });

  try {
    const GOOGLE_AI_API_KEY = Deno.env.get("GOOGLE_AI_API_KEY");
    if (!GOOGLE_AI_API_KEY) throw new Error("GOOGLE_AI_API_KEY is not configured");

    const SUPABASE_URL = Deno.env.get("SUPABASE_URL");
    const SUPABASE_SERVICE_ROLE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");
    if (!SUPABASE_URL || !SUPABASE_SERVICE_ROLE_KEY) throw new Error("Supabase config missing");

    const { text, model, voiceName, sceneIndex, projectName } = await req.json();
    if (!text) throw new Error("text is required");

    const ttsModel = model || "gemini-2.5-flash-preview-tts";
    const voice = voiceName || "Kore"; // Deep, authoritative narrator voice
    const apiUrl = `https://generativelanguage.googleapis.com/v1beta/models/${ttsModel}:generateContent?key=${GOOGLE_AI_API_KEY}`;

    const requestBody = {
      contents: [{
        parts: [{ text }],
      }],
      generationConfig: {
        responseModalities: ["AUDIO"],
        speechConfig: {
          voiceConfig: {
            prebuiltVoiceConfig: {
              voiceName: voice,
            },
          },
        },
      },
    };

    console.log(`Calling Gemini TTS: model=${ttsModel}, voice=${voice}, text length=${text.length}, scene=${sceneIndex ?? 'full'}`);

    const response = await fetch(apiUrl, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(requestBody),
    });

    if (!response.ok) {
      const errorText = await response.text();
      console.error("TTS API error:", response.status, errorText);

      if (response.status === 429) {
        return new Response(JSON.stringify({
          error: "API quota exceeded. Wait a few minutes and try again.",
          errorCode: "RATE_LIMITED",
        }), {
          status: 429,
          headers: { ...corsHeaders, "Content-Type": "application/json" },
        });
      }

      return new Response(JSON.stringify({
        error: `TTS API error (${response.status})`,
        details: errorText.substring(0, 500),
      }), {
        status: response.status,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const data = await response.json();

    // Extract audio from Gemini TTS response
    const audioPart = data.candidates?.[0]?.content?.parts?.find(
      (p: any) => p.inlineData?.mimeType?.startsWith("audio/")
    );

    if (!audioPart?.inlineData) {
      console.error("No audio in TTS response:", JSON.stringify(data).substring(0, 500));
      return new Response(JSON.stringify({
        error: "No audio generated by TTS model",
        details: "The model did not return audio. Try shorter text.",
      }), {
        status: 500,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const audioBase64 = audioPart.inlineData.data;
    const mimeType = audioPart.inlineData.mimeType; // typically audio/L16 or audio/wav

    // Determine file extension from mime type
    const ext = mimeType.includes("wav") ? "wav" : mimeType.includes("mp3") ? "mp3" : "wav";

    // Upload to storage
    const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY);
    const safeName = (projectName || "project").replace(/[^a-zA-Z0-9_-]/g, "_");
    const sceneLabel = sceneIndex !== undefined && sceneIndex !== null ? `scene_${sceneIndex + 1}` : "full_narration";
    const fileName = `${safeName}/audio/${sceneLabel}_${Date.now()}.${ext}`;
    const audioBytes = Uint8Array.from(atob(audioBase64), (c) => c.charCodeAt(0));

    const { error: uploadError } = await supabase.storage
      .from("bunker-assets")
      .upload(fileName, audioBytes, { contentType: mimeType, upsert: true });

    if (uploadError) {
      console.error("Storage upload error:", uploadError);
      return new Response(JSON.stringify({
        audioUrl: `data:${mimeType};base64,${audioBase64}`,
        mimeType,
        storageError: uploadError.message,
      }), {
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const { data: publicUrl } = supabase.storage
      .from("bunker-assets")
      .getPublicUrl(fileName);

    return new Response(JSON.stringify({
      audioUrl: publicUrl.publicUrl,
      mimeType,
      storagePath: fileName,
    }), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  } catch (e) {
    console.error("tts-generate error:", e);
    return new Response(JSON.stringify({ error: e instanceof Error ? e.message : "Unknown error" }), {
      status: 500,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});
