import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version",
};

serve(async (req) => {
  if (req.method === "OPTIONS") return new Response("ok", { headers: corsHeaders });

  try {
    const GOOGLE_AI_API_KEY = Deno.env.get("GOOGLE_AI_API_KEY");
    if (!GOOGLE_AI_API_KEY) throw new Error("GOOGLE_AI_API_KEY is not configured");

    const SUPABASE_URL = Deno.env.get("SUPABASE_URL");
    const SUPABASE_SERVICE_ROLE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");
    if (!SUPABASE_URL || !SUPABASE_SERVICE_ROLE_KEY) throw new Error("Supabase config missing");

    const { prompt, model, referenceImageBase64, sceneIndex, projectName } = await req.json();
    if (!prompt) throw new Error("prompt is required");

    const idx = sceneIndex ?? -1;
    const noWorkersScenes = [0, 8];
    const personGeneration = noWorkersScenes.includes(idx) ? "DONT_ALLOW" : "ALLOW_ADULT";
    const hasPrevRef = !!referenceImageBase64;
    console.log(`Scene ${idx + 1}: personGeneration=${personGeneration}, hasPrevRef=${hasPrevRef}`);

    let imageBase64: string;

    if (hasPrevRef) {
      // Use Lovable AI Gateway with Gemini image model — sequential chain reference
      const LOVABLE_API_KEY = Deno.env.get("LOVABLE_API_KEY");
      if (!LOVABLE_API_KEY) throw new Error("LOVABLE_API_KEY is not configured");

      const contentParts: any[] = [];

      // Sequential instruction: only previous scene as reference
      const instruction = buildSequentialInstruction(prompt, idx);
      contentParts.push({ type: "text", text: instruction });

      const cleanPrev = referenceImageBase64.includes(",") ? referenceImageBase64.split(",")[1] : referenceImageBase64;
      contentParts.push({ type: "text", text: `[REFERENCE — Scene ${idx}. This is the immediately previous approved image. The new image must continue directly from this state. Preserve structure, camera, and environment. Only apply the changes described in the scene prompt.]` });
      contentParts.push({
        type: "image_url",
        image_url: { url: `data:image/png;base64,${cleanPrev}` },
      });

      console.log(`Using Lovable AI (Gemini image model) with previous scene reference for scene ${idx + 1}`);

      const geminiResponse = await fetch("https://ai.gateway.lovable.dev/v1/chat/completions", {
        method: "POST",
        headers: {
          Authorization: `Bearer ${LOVABLE_API_KEY}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          model: "google/gemini-3-pro-image-preview",
          messages: [{ role: "user", content: contentParts }],
          modalities: ["image", "text"],
        }),
      });

      if (!geminiResponse.ok) {
        const errText = await geminiResponse.text();
        console.error("Lovable AI error:", geminiResponse.status, errText);

        if (geminiResponse.status === 429) {
          return new Response(JSON.stringify({
            error: "Rate limit exceeded. Wait a moment and try again.",
            errorCode: "RATE_LIMITED",
          }), { status: 429, headers: { ...corsHeaders, "Content-Type": "application/json" } });
        }
        if (geminiResponse.status === 402) {
          return new Response(JSON.stringify({
            error: "AI credits exhausted. Please add credits in Settings → Workspace → Usage.",
            errorCode: "PAYMENT_REQUIRED",
          }), { status: 402, headers: { ...corsHeaders, "Content-Type": "application/json" } });
        }
        throw new Error(`Lovable AI error (${geminiResponse.status}): ${errText.substring(0, 300)}`);
      }

      const geminiData = await geminiResponse.json();
      const generatedImage = geminiData.choices?.[0]?.message?.images?.[0]?.image_url?.url;

      if (!generatedImage) {
        console.error("No image in Gemini response:", JSON.stringify(geminiData).substring(0, 500));
        throw new Error("No image generated by Gemini image model");
      }

      imageBase64 = generatedImage.includes(",") ? generatedImage.split(",")[1] : generatedImage;
      console.log(`Scene ${idx + 1} generated via Lovable AI (sequential chain)`);

    } else {
      // Scene 1 or no reference: use Imagen 4 directly
      const imagenModel = model || "imagen-4.0-generate-001";
      const apiUrl = `https://generativelanguage.googleapis.com/v1beta/models/${imagenModel}:predict?key=${GOOGLE_AI_API_KEY}`;

      const requestBody = {
        instances: [{ prompt }],
        parameters: {
          sampleCount: 1,
          aspectRatio: "9:16",
          personGeneration,
          safetyFilterLevel: "BLOCK_MEDIUM_AND_ABOVE",
        },
      };

      console.log(`Calling Imagen 4: model=${imagenModel}, prompt length=${prompt.length}`);

      const response = await fetch(apiUrl, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(requestBody),
      });

      if (!response.ok) {
        const errorText = await response.text();
        console.error("Imagen 4 API error:", response.status, errorText);

        if (response.status === 429) {
          return new Response(JSON.stringify({
            error: "API quota exceeded. Wait a few minutes and try again.",
            errorCode: "RATE_LIMITED",
          }), { status: 429, headers: { ...corsHeaders, "Content-Type": "application/json" } });
        }

        return new Response(JSON.stringify({
          error: `Imagen 4 API error (${response.status})`,
          details: errorText.substring(0, 500),
        }), { status: response.status, headers: { ...corsHeaders, "Content-Type": "application/json" } });
      }

      const data = await response.json();
      const prediction = data.predictions?.[0];
      if (!prediction?.bytesBase64Encoded) {
        console.error("No image in Imagen 4 response:", JSON.stringify(data).substring(0, 500));
        return new Response(JSON.stringify({
          error: "No image generated by Imagen 4",
          details: "The model did not return an image. Try simplifying the prompt.",
        }), { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } });
      }

      imageBase64 = prediction.bytesBase64Encoded;
      console.log(`Scene ${idx + 1} generated via Imagen 4`);
    }

    // Upload to Cloud storage
    const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY);
    const safeName = (projectName || "project").replace(/[^a-zA-Z0-9_-]/g, "_");
    const fileName = `${safeName}/scenes/scene_${(sceneIndex ?? 0) + 1}_${Date.now()}.png`;
    const imageBytes = Uint8Array.from(atob(imageBase64), (c) => c.charCodeAt(0));

    const { error: uploadError } = await supabase.storage
      .from("bunker-assets")
      .upload(fileName, imageBytes, { contentType: "image/png", upsert: true });

    if (uploadError) {
      console.error("Storage upload error:", uploadError);
      return new Response(JSON.stringify({
        imageUrl: `data:image/png;base64,${imageBase64}`,
        imageBase64,
        storageError: uploadError.message,
      }), { headers: { ...corsHeaders, "Content-Type": "application/json" } });
    }

    const { data: publicUrl } = supabase.storage
      .from("bunker-assets")
      .getPublicUrl(fileName);

    return new Response(JSON.stringify({
      imageUrl: publicUrl.publicUrl,
      imageBase64,
      storagePath: fileName,
    }), { headers: { ...corsHeaders, "Content-Type": "application/json" } });

  } catch (e) {
    console.error("imagen-generate error:", e);
    return new Response(JSON.stringify({ error: e instanceof Error ? e.message : "Unknown error" }), {
      status: 500,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});

/**
 * Build sequential chain instruction for Gemini image generation.
 * Only the immediately previous scene is used as reference.
 */
function buildSequentialInstruction(prompt: string, sceneIndex: number): string {
  const parts: string[] = [];

  parts.push(`Generate a new image for scene ${sceneIndex + 1} of a bunker restoration timelapse. The image must be vertical 9:16 format, hyper-realistic, cinematic. Do not include any text, labels, watermarks, metadata, or written words anywhere in the image.`);
  parts.push('');
  parts.push(`Scene description: ${prompt}`);
  parts.push('');
  parts.push(`The attached image is the immediately previous scene. Your new image must be a direct continuation from it. Preserve the bunker structure, camera angle, environment, and composition exactly. Only apply the minimal changes described above. The transition must feel gradual and believable. Do not invent a new bunker design, change the camera angle, or make dramatic jumps in restoration state.`);

  return parts.join('\n');
}
